# Generated by Django 6.1 on 2026-08-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Aksi yang dilakukan (contoh: LOGIN, SCAN_FIREWALL, CREATE_DEVICE)', max_length=150)),
                ('target_type', models.CharField(blank=True, help_text='Model/Objek yang terdampak (contoh: Device, ComplianceRule)', max_length=100, null=True)),
                ('target_id', models.IntegerField(blank=True, help_text='ID record dari tabel yang terdampak', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP Address pengguna saat melakukan aksi', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Waktu kejadian')),
                ('details', models.JSONField(blank=True, help_text='Data tambahan atau perubahan yang terjadi (snapshot JSON sebelum/sesudah)', null=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
