# Generated by Django 6.1 on 2026-08-06 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_code', models.CharField(help_text='Kode unik rule, misal: POL_ANY_ANY', max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('POLICY', 'Firewall Policy'), ('INTERFACE', 'Interface'), ('ROUTING', 'Routing'), ('ADDRESS', 'Address Object'), ('SERVICE', 'Service Object'), ('ADMIN', 'Administrator')], max_length=20)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Info')], max_length=15)),
                ('description', models.TextField()),
                ('impact', models.TextField(help_text='Dampak jika rule ini dilanggar')),
                ('recommendation', models.TextField(help_text='Rekomendasi perbaikan')),
                ('is_active', models.BooleanField(default=True, help_text='Nonaktifkan jika rule tidak ingin dievaluasi')),
                ('penalty_score', models.PositiveIntegerField(default=0, help_text='Pengurangan skor jika rule dilanggar. (Crit:20, High:10, Med:5, Low:2)')),
            ],
            options={
                'verbose_name': 'Compliance Rule',
                'verbose_name_plural': 'Compliance Rules',
                'db_table': 'compliance_rules',
            },
        ),
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('compliance_score', models.IntegerField(default=100, help_text='Skor kepatuhan (0-100)')),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='RUNNING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='devices.device')),
            ],
            options={
                'verbose_name': 'Scan History',
                'verbose_name_plural': 'Scan Histories',
                'db_table': 'scan_histories',
                'ordering': ['-scan_date'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_name', models.CharField(help_text='Nama elemen yang melanggar (misal: Policy ID 5)', max_length=255)),
                ('element_details', models.JSONField(blank=True, help_text='Raw data JSON dari elemen yang melanggar', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='compliance.compliancerule')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='compliance.scanhistory')),
            ],
            options={
                'verbose_name': 'Finding',
                'verbose_name_plural': 'Findings',
                'db_table': 'scan_findings',
            },
        ),
    ]
