# Generated by Django 6.1 on 2026-08-17 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancerule',
            name='impact',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='compliancerule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='compliancerule',
            name='penalty_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='compliancerule',
            name='recommendation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='compliancerule',
            name='rule_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='finding',
            name='element_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finding',
            name='element_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scanhistory',
            name='compliance_score',
            field=models.IntegerField(default=100),
        ),
        migrations.CreateModel(
            name='PolicyRiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.CharField(max_length=50)),
                ('policy_name', models.CharField(blank=True, max_length=200, null=True)),
                ('risk_score', models.IntegerField(default=0, help_text='Nilai risiko 0-100')),
                ('severity', models.CharField(help_text='LOW, MEDIUM, HIGH, CRITICAL', max_length=20)),
                ('contributing_factors', models.JSONField(default=list, help_text='Alasan pembentukan risk score')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_risks', to='compliance.scanhistory')),
            ],
            options={
                'db_table': 'policy_risk_assessments',
                'ordering': ['-risk_score'],
            },
        ),
    ]
