# Generated by Django 6.1 on 2026-08-17 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_alter_compliancerule_impact_and_more'),
        ('devices', '0002_alter_device_api_token_encrypted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finding',
            options={},
        ),
        migrations.AlterModelOptions(
            name='scanhistory',
            options={'ordering': ['-scan_date']},
        ),
        migrations.AlterField(
            model_name='policyriskassessment',
            name='contributing_factors',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='policyriskassessment',
            name='risk_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='policyriskassessment',
            name='severity',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='ChangeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('changes_detail', models.JSONField(default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_notifications', to='devices.device')),
            ],
            options={
                'db_table': 'change_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policies_json', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_snapshot', to='devices.device')),
            ],
        ),
    ]
