# Generated by Django 6.1 on 2026-08-17 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_alter_finding_options_alter_scanhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compliancerule',
            options={},
        ),
        migrations.AddField(
            model_name='changenotification',
            name='scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_notifications', to='compliance.scanhistory'),
        ),
    ]
