# Generated by Django 6.1 on 2026-09-10 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0004_alter_compliancerule_options_changenotification_scan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policyriskassessment',
            options={},
        ),
        migrations.RemoveField(
            model_name='policyriskassessment',
            name='risk_score',
        ),
    ]
