# Generated by Django 6.1 on 2026-09-10 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0005_alter_policyriskassessment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compliancerule',
            name='penalty_score',
        ),
    ]
