# Generated by Django 6.1 on 2026-09-14 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0006_remove_compliancerule_penalty_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanhistory',
            name='compliance_score',
        ),
    ]
