# Generated by Django 6.1 on 2026-09-15 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0007_remove_scanhistory_compliance_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='changes_detail',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.DeleteModel(
            name='ChangeNotification',
        ),
    ]
