# Generated by Django 6.1 on 2026-09-21 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0008_scanhistory_changes_detail_delete_changenotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanhistory',
            name='changes_detail',
        ),
        migrations.DeleteModel(
            name='ConfigurationSnapshot',
        ),
    ]
