# Generated by Django 6.1 on 2026-08-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nama identifikasi perangkat (contoh: Core-FW-HQ)', max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(help_text='IP Address Management FortiGate')),
                ('port', models.PositiveIntegerField(default=443, help_text='Port manajemen (biasanya 443 untuk HTTPS)')),
                ('api_token_encrypted', models.TextField(help_text='Token API FortiGate (terenkripsi)')),
                ('os_version', models.CharField(blank=True, help_text='Versi FortiOS (didapatkan otomatis saat sync)', max_length=50, null=True)),
                ('connection_status', models.CharField(choices=[('CONNECTED', 'Connected'), ('DISCONNECTED', 'Disconnected'), ('ERROR', 'Connection Error'), ('UNTESTED', 'Untested')], default='UNTESTED', help_text='Status koneksi terakhir ke perangkat', max_length=20)),
                ('last_sync', models.DateTimeField(blank=True, help_text='Waktu terakhir konfigurasi berhasil ditarik', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Firewall Device',
                'verbose_name_plural': 'Firewall Devices',
                'db_table': 'firewall_devices',
                'unique_together': {('ip_address', 'port')},
            },
        ),
    ]
