# Generated by Django 6.1 on 2026-08-07 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='api_token_encrypted',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='connection_status',
            field=models.CharField(choices=[('CONNECTED', 'Connected'), ('DISCONNECTED', 'Disconnected'), ('ERROR', 'Connection Error'), ('UNTESTED', 'Untested')], default='UNTESTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='os_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='port',
            field=models.PositiveIntegerField(default=443),
        ),
        migrations.CreateModel(
            name='DeviceStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_interfaces_up', models.IntegerField(default=0)),
                ('total_policies', models.IntegerField(default=0)),
                ('top_used_policy', models.CharField(blank=True, help_text='Policy dengan hit tertinggi', max_length=255, null=True)),
                ('never_used_policies_count', models.IntegerField(default=0, help_text='Jumlah policy dengan 0 hit')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='devices.device')),
            ],
            options={
                'db_table': 'device_statistics',
            },
        ),
    ]
