# Generated by Django 6.1 on 2026-09-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_api_token_encrypted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_config_hash',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
