# Generated by Django 6.1 on 2026-09-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_last_config_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='last_config_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
