# Generated by Django 6.1 on 2026-09-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_device_last_config_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicestatistic',
            name='total_users',
            field=models.IntegerField(default=0, help_text='Jumlah administrator/user yang terdaftar'),
        ),
    ]
