# Generated by Django 6.1 on 2026-09-20 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_devicestatistic_total_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicestatistic',
            name='top_used_policy',
        ),
    ]
