# Generated by Django 6.1 on 2026-09-20 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_remove_devicestatistic_top_used_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicestatistic',
            name='total_users',
        ),
    ]
