# Generated by Django 6.1 on 2026-09-24 13:18

import devices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_remove_devicestatistic_total_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(validators=[devices.models.validate_non_loopback]),
        ),
    ]
