# Generated by Django 6.1 on 2026-09-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text='Nama role (contoh: Administrator)', max_length=50, unique=True),
        ),
    ]
