# Generated by Django 6.1 on 2026-09-21 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_role_is_system_admin_alter_role_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='is_system_admin',
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, help_text='Deskripsi hak akses role ini.', null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text='Nama role (contoh: Administrator)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Role yang menentukan tingkat akses pengguna dalam aplikasi.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='authentication.role'),
        ),
    ]
